const data = {
    products: [
          {
            _id: '1',
            name: 'Pixel Nova Shirt',
            category: 'Shirts',
            image: '/images/pixel-01.svg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            _id: '2',
            name: 'Pixel Drift Shirt',
            category: 'Shirts',
            image: '/images/pixel-02.svg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            _id: '3',
            name: 'Pixel Ember Shirt',
            category: 'Shirts',
            image: '/images/pixel-03.svg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
          },
          {
            _id: '4',
            name: 'Pixel Tide Pant',
            category: 'Pants',
            image: '/images/pixel-04.svg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
          },
          {
            _id: '5',
            name: 'Pixel Grove Pant',
            category: 'Pants',
            image: '/images/pixel-05.svg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            _id: '6',
            name: 'Pixel Pulse Pant',
            category: 'Pants',
            image: '/images/pixel-06.svg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
          },
          {
            _id: '7',
            name: 'Pixel Carbon Shoes',
            category: 'Shoes',
            image: '/images/pixel-07.svg',
            price: 169,
            countInStock: 8,
            brand: 'Vector',
            rating: 4.7,
            numReviews: 11,
            description: 'high quality product',
          },
          {
            _id: '8',
            name: 'Pixel Sky Shoes',
            category: 'Shoes',
            image: '/images/pixel-08.svg',
            price: 189,
            countInStock: 9,
            brand: 'Orbit',
            rating: 4.6,
            numReviews: 13,
            description: 'high quality product',
          }
    ]
}

export default data;
